import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const dictionary = {
  en: {
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': "Here's where you stand today, and what to tackle next.",
    'dashboard.continue': 'Continue training',
    'dashboard.cohort': 'Cohort 2026',
    'dashboard.track': 'Track',
    'dashboard.major': 'MAJOR',
    'dashboard.occupationGoal': 'OCCUPATION GOAL',
    'dashboard.targeting': 'Targeting',
    'dashboard.goals': 'GOALS',
    'dashboard.goal1': 'Reach Work-Ready Score 85',
    'dashboard.goal2': 'Ship 3 mentor-reviewed memos',
    'dashboard.goal3': 'Land summer internship',
    'dashboard.viewPortfolio': 'View Portfolio',
    'dashboard.portfolioSub': '9 mentor-reviewed evidence items',
    'dashboard.viewFeedback': 'View Feedback',
    'dashboard.feedbackSub': 'Mentor + AI coach notes on your work',
    'dashboard.checkReadiness': 'Check Readiness Score',
    'dashboard.againstTrack': 'against',
    'dashboard.yourTrack': 'your track',
    'dashboard.workReadyScore': 'WORK-READY SCORE',
    'dashboard.vs': 'vs',
    'dashboard.scenariosCompleted': 'SCENARIOS COMPLETED',
    'dashboard.rcaRating': 'RCA COACH RATING',
    'dashboard.streak': 'STREAK',
    'dashboard.breakdownTitle': 'Work-Ready Score breakdown',
    'dashboard.breakdownSub': 'Weighted coverage of skills required for Backend Software Engineer against your current levels.',
    'dashboard.biggestGap': 'Biggest gap:',
    'dashboard.weight': 'w',
    'dashboard.scoreFormula': "Score = Σ (skill coverage × occupation weight). Coverage is capped at the role's target per skill.",
    'dashboard.upcomingTitle': 'Upcoming scenarios',
    'dashboard.viewAll': 'View all',
    'dashboard.open': 'Open',
    'dashboard.topGaps': 'Top skill gaps',
    'dashboard.fullAssessment': 'Full assessment',
    'dashboard.badgesEarned': 'Badges earned',
    'dashboard.badge1': 'Clean Coder',
    'dashboard.badge2': 'Incident Responder',
    'dashboard.badge3': 'Code Reviewer',
    'dashboard.badge4': 'System Designer',
    'dashboard.thisWeek': 'This week',
    'dashboard.thisWeekDesc': '3 scenarios, 2 RCA reviews, 1 memo drafted.',
    'dashboard.nextSync': 'Next mentor sync',
    'dashboard.nextSyncDesc': 'Fri, 12:30 PM with M. Iyer (Staff Engineer, Razorpay).',
    'port.title': 'Evidence Portfolio',
    'port.subtitle': 'Every solved scenario becomes verified proof recruiters and mentors can trust.',
    'port.shareAlert': 'Recruiter access link copied to clipboard!',
    'port.share': 'Share with recruiters',
    'port.artifacts': 'ARTIFACTS',
    'port.completed': 'completed',
    'port.totalPoints': 'TOTAL POINTS',
    'port.acrossEvidence': 'across all evidence',
    'port.mentorReviews': 'MENTOR REVIEWS',
    'port.last30': 'in the last 30 days',
    'port.readinessKpi': 'READINESS KPI',
    'port.jobReady': 'job-ready tier',
    'port.evidenceList': 'Evidence List',
    'port.evidenceSubtitle': 'Your latest verified submissions.',
    'port.statusCompleted': 'Completed',
    'port.statusNeedsReview': 'Needs review',
    'port.statusNeedsRevision': 'Needs revision',
    'port.readinessScore': 'READINESS SCORE',
    'port.readinessDesc': 'You are currently in the 76th percentile for Backend Software Engineer readiness.',
    'port.submit': 'Submit for Review',
    'port.submitDesc': 'You have 1 item ready to be sent to your mentor for detailed feedback.',
    'port.submitBtn': 'Submit selected items',
    'port.submitNote': 'Usually reviewed within 48 hours',
    'port.mentorFeedback': 'Mentor Feedback & Highlights',
    'port.mentorFeedbackDesc': 'What industry experts are saying about your work.',
    'port.solvedScenario': 'Solved Scenario',
    'port.scoreLabel': 'Score',
    'port.returnApp': 'Return to App',
    'quiz.title': 'Initial Skill Gap Assessment',
    'quiz.questionStep': 'QUESTION {current} OF {total}',
    'quiz.answered': 'answered',
    'quiz.btnPrev': 'Previous',
    'quiz.btnNext': 'Next →',
    'quiz.btnSaving': 'Saving...',
    'quiz.btnFinish': 'Finish & View Profile →',
    'aiquiz.title': 'AI Occupation Simulator Quiz',
    'aiquiz.generatingTitle': 'Generating your personalized {occupationGoal} assessment...',
    'aiquiz.generatingDesc': 'Our AI is designing 50 questions to test your core skills. This may take a minute...',
    'aiquiz.error': 'Error',
    'aiquiz.btnClose': 'Close',
    'aiquiz.btnScoring': 'Scoring...',
    'aiquiz.btnFinish': 'Finish Assessment →',
    // basic placeholders for quiz questions if missing
    'quiz.q1': 'How comfortable are you with drawing end-to-end process maps?',
    'quiz.q1_o1': "I don't know how to create process maps.",
    'quiz.q1_o2': "I can create basic flowcharts but struggle with complex workflows.",
    'quiz.q1_o3': "I can confidently draw detailed end-to-end process maps for unfamiliar workflows.",
    'quiz.q2': 'How would you rate your ability to identify safety and quality risks?',
    'quiz.q2_o1': "I rarely consider edge-case safety regressions.",
    'quiz.q2_o2': "I can identify common risks but might miss complex system interactions.",
    'quiz.q2_o3': "I can independently spot edge-case safety or quality regressions in existing systems.",
    'quiz.q3': 'How experienced are you with Root Cause Analysis (RCA)?',
    'quiz.q3_o1': "I usually just fix the immediate bug without structured analysis.",
    'quiz.q3_o2': "I know what RCA is but haven't run structured 5-Whys or fishbone reviews.",
    'quiz.q3_o3': "I know how to run a structured 5-Whys or fishbone analysis to find true root causes.",
    'quiz.q4': 'How well can you trace artifacts back to their source?',
    'quiz.q4_o1': "I find it difficult to connect requirements with code and tests.",
    'quiz.q4_o2': "I can somewhat trace artifacts but sometimes get lost in complex systems.",
    'quiz.q4_o3': "I can trace logs, metrics, or artifacts back to their source without getting lost.",
    'quiz.q5': 'How comfortable are you writing technical incident memos?',
    'quiz.q5_o1': "I have never written a technical incident report.",
    'quiz.q5_o2': "I can write a report but it's often unstructured or too detailed.",
    'quiz.q5_o3': "I can write a crisp 1-page technical memo outlining an incident, root cause, and next steps.",
    'quiz.q6': 'How well do you understand Responsible AI practices?',
    'quiz.q6_o1': "I am unfamiliar with designing features for fairness and avoiding bias.",
    'quiz.q6_o2': "I have a basic understanding but lack practical experience evaluating AI bias.",
    'quiz.q6_o3': "I understand how to design and evaluate features to avoid bias and ensure fairness."
  },
  th: {
    'dashboard.welcome': 'ยินดีต้อนรับกลับมา',
    'dashboard.subtitle': 'นี่คือสถานะของคุณในวันนี้ และสิ่งที่คุณควรทำต่อไป',
    'dashboard.continue': 'ฝึกฝนต่อไป',
    'dashboard.cohort': 'รุ่นปี 2026',
    'dashboard.track': 'สายงาน',
    'dashboard.major': 'สาขาวิชา',
    'dashboard.occupationGoal': 'เป้าหมายอาชีพ',
    'dashboard.targeting': 'ตั้งเป้าหมายไปที่',
    'dashboard.goals': 'เป้าหมาย',
    'dashboard.goal1': 'ทำคะแนนความพร้อมทำงานให้ถึง 85',
    'dashboard.goal2': 'ส่งบทความ/บันทึกเทคนิคให้เมนเทอร์ตรวจ 3 ชิ้น',
    'dashboard.goal3': 'ได้ที่ฝึกงานช่วงซัมเมอร์',
    'dashboard.viewPortfolio': 'ดูแฟ้มผลงาน',
    'dashboard.portfolioSub': 'มีผลงานที่ผ่านการตรวจจากเมนเทอร์แล้ว 9 ชิ้น',
    'dashboard.viewFeedback': 'ดูข้อเสนอแนะ',
    'dashboard.feedbackSub': 'โน้ตจากเมนเทอร์และ AI โค้ชเกี่ยวกับผลงานของคุณ',
    'dashboard.checkReadiness': 'ตรวจสอบคะแนนความพร้อม',
    'dashboard.againstTrack': 'เทียบกับ',
    'dashboard.yourTrack': 'สายงานของคุณ',
    'dashboard.workReadyScore': 'คะแนนความพร้อมทำงาน',
    'dashboard.vs': 'เทียบกับ',
    'dashboard.scenariosCompleted': 'สถานการณ์ที่ผ่านแล้ว',
    'dashboard.rcaRating': 'คะแนนการวิเคราะห์ต้นตอปัญหา (RCA)',
    'dashboard.streak': 'ความต่อเนื่อง (STREAK)',
    'dashboard.breakdownTitle': 'รายละเอียดคะแนนความพร้อมทำงาน',
    'dashboard.breakdownSub': 'การครอบคลุมของทักษะที่จำเป็นสำหรับ Backend Software Engineer เมื่อเทียบกับระดับปัจจุบันของคุณ (คิดตามน้ำหนัก)',
    'dashboard.biggestGap': 'ช่องว่างที่ใหญ่ที่สุด:',
    'dashboard.weight': 'น้ำหนัก',
    'dashboard.scoreFormula': "คะแนน = Σ (การครอบคลุมของทักษะ × น้ำหนักของอาชีพ). การครอบคลุมจะถูกจำกัดไว้ที่เป้าหมายของบทบาทต่อทักษะ",
    'dashboard.upcomingTitle': 'สถานการณ์ถัดไป',
    'dashboard.viewAll': 'ดูทั้งหมด',
    'dashboard.open': 'เปิด',
    'dashboard.topGaps': 'ทักษะที่ต้องพัฒนาสูงสุด',
    'dashboard.fullAssessment': 'ดูการประเมินฉบับเต็ม',
    'dashboard.badgesEarned': 'ป้ายแห่งความสำเร็จที่ได้รับ',
    'dashboard.badge1': 'นักเขียนโค้ดที่สะอาด (Clean Coder)',
    'dashboard.badge2': 'ผู้ตอบสนองต่อเหตุการณ์ (Incident Responder)',
    'dashboard.badge3': 'ผู้ตรวจสอบโค้ด (Code Reviewer)',
    'dashboard.badge4': 'นักออกแบบระบบ (System Designer)',
    'dashboard.thisWeek': 'สัปดาห์นี้',
    'dashboard.thisWeekDesc': 'จำลอง 3 สถานการณ์, รีวิว RCA 2 ครั้ง, ร่างเอกสาร 1 ชิ้น',
    'dashboard.nextSync': 'นัดพบเมนเทอร์ครั้งถัดไป',
    'dashboard.nextSyncDesc': 'วันศุกร์, 12:30 น. กับ M. Iyer (Staff Engineer, Razorpay)',
    'port.title': 'แฟ้มผลงานแห่งความพร้อม (Evidence Portfolio)',
    'port.subtitle': 'ทุกสถานการณ์ที่คุณแก้ได้คือเครื่องพิสูจน์ที่แท้จริงให้ Recruiter และ Mentor มั่นใจ',
    'port.shareAlert': 'คัดลอกลิงก์สำหรับส่งให้ Recruiter แล้ว!',
    'port.share': 'แชร์ให้ Recruiter',
    'port.artifacts': 'ผลงานทั้งหมด',
    'port.completed': 'ทำเสร็จแล้ว',
    'port.totalPoints': 'คะแนนรวม',
    'port.acrossEvidence': 'จากผลงานทั้งหมด',
    'port.mentorReviews': 'รับคำแนะนำจาก Mentor',
    'port.last30': 'ใน 30 วันที่ผ่านมา',
    'port.readinessKpi': 'ดัชนีความพร้อม (READINESS)',
    'port.jobReady': 'อยู่ในเกณฑ์พร้อมทำงาน',
    'port.evidenceList': 'รายการผลงาน (Evidence List)',
    'port.evidenceSubtitle': 'ผลงานล่าสุดที่คุณได้รับการยืนยัน',
    'port.statusCompleted': 'เสร็จสมบูรณ์',
    'port.statusNeedsReview': 'รอการตรวจ',
    'port.statusNeedsRevision': 'ต้องแก้ไข',
    'port.readinessScore': 'คะแนนความพร้อมโดยรวม',
    'port.readinessDesc': 'ตอนนี้คุณอยู่ในเปอร์เซ็นไทล์ที่ 76 สำหรับความพร้อมทำงานในตำแหน่ง Backend Software Engineer',
    'port.submit': 'ส่งงานให้ Mentor ตรวจ',
    'port.submitDesc': 'คุณมี 1 รายการที่พร้อมส่งให้ Mentor ช่วยดูและให้ฟีดแบ็กแบบละเอียด',
    'port.submitBtn': 'ส่งรายการที่เลือก',
    'port.submitNote': 'โดยปกติจะได้รับการตอบกลับภายใน 48 ชั่วโมง',
    'port.mentorFeedback': 'ฟีดแบ็กและไฮไลท์จาก Mentor',
    'port.mentorFeedbackDesc': 'สิ่งที่ผู้เชี่ยวชาญในวงการพูดถึงผลงานของคุณ',
    'port.solvedScenario': 'จำลองสถานการณ์ที่',
    'port.scoreLabel': 'คะแนน',
    'port.returnApp': 'กลับสู่หน้าหลักแอป',
    'quiz.title': 'แบบประเมินความสามารถเริ่มต้น',
    'quiz.questionStep': 'คำถามที่ {current} จาก {total}',
    'quiz.answered': 'ตอบแล้ว',
    'quiz.btnPrev': 'ย้อนกลับ',
    'quiz.btnNext': 'ถัดไป →',
    'quiz.btnSaving': 'กำลังบันทึก...',
    'quiz.btnFinish': 'เสร็จสิ้น & ดูโปรไฟล์ →',
    'aiquiz.title': 'แบบทดสอบ AI จำลองสถานการณ์อาชีพ',
    'aiquiz.generatingTitle': 'กำลังสร้างแบบประเมินสำหรับ {occupationGoal} ให้คุณโดยเฉพาะ...',
    'aiquiz.generatingDesc': 'AI ของเรากำลังออกแบบคำถาม 50 ข้อเพื่อทดสอบทักษะหลักของคุณ อาจใช้เวลาสักครู่...',
    'aiquiz.error': 'ข้อผิดพลาด',
    'aiquiz.btnClose': 'ปิด',
    'aiquiz.btnScoring': 'กำลังให้คะแนน...',
    'aiquiz.btnFinish': 'เสร็จสิ้นการประเมิน →',
    // questions translate
    'quiz.q1': 'คุณมีความชำนาญในการวาดแผนผังกระบวนการแบบครบวงจร (End-to-End) แค่ไหน?',
    'quiz.q1_o1': "ฉันไม่รู้ว่าต้องสร้างกระบวนการเหล่านี้อย่างไร",
    'quiz.q1_o2': "ฉันพอสร้าง Flowchart เบื้องต้นได้ แต่ยังติดขัดในระบบที่ซับซ้อน",
    'quiz.q1_o3': "ฉันสามารถวาดแผนผังที่มีรายละเอียดได้อย่างมั่นใจแม้เป็นระบบที่ไม่คุ้นเคย",
    'quiz.q2': 'คุณประเมินความสามารถของตนเองในการระบุความเสี่ยงด้านความปลอดภัยและคุณภาพในระดับใด?',
    'quiz.q2_o1': "ฉันแทบจะไม่ได้คิดถึงปัญหาด้านความปลอดภัยเลย",
    'quiz.q2_o2': "ฉันระบุความเสี่ยงทั่วไปได้ แต่อาจพลาดปฏิสัมพันธ์ของระบบที่ซับซ้อน",
    'quiz.q2_o3': "ฉันระบุจุดบกพร่องเล็กๆ น้อยๆ หรือปัญหาคุณภาพในระบบที่มีอยู่ได้ด้วยตัวเอง",
    'quiz.q3': 'คุณมีประสบการณ์ในการวิเคราะห์หาสาเหตุที่แท้จริง (RCA) แค่ไหน?',
    'quiz.q3_o1': "ฉันมักจะแก้บั๊กแค่ตรงหน้าโดยไม่ได้วิเคราะห์เป็นระบบ",
    'quiz.q3_o2': "ฉันรู้จัก RCA แต่ไม่เคยทำแบบโครงสร้าง (เช่น 5-Whys หรือ Fishbone)",
    'quiz.q3_o3': "ฉันสามารถรัน 5-Whys หรือ Fishbone analysis เพื่อหา root cause ได้อย่างชำนาญ",
    'quiz.q4': 'คุณสามารถแกะรอยและเชื่อมโยงผลงานหรือโค้ดกลับไปยังแหล่งที่มาได้ดีแค่ไหน?',
    'quiz.q4_o1': "ฉันรู้สึกยากที่จะเชื่อมโยง Requirements กับ Code และ Tests",
    'quiz.q4_o2': "พอทำได้บ้าง แต่บางครั้งก็หลงทางในระบบที่ใหญ่เกินไป",
    'quiz.q4_o3': "ฉันแกะรอย Logs, Metrics, หรือ Artifacts กลับไปหาแหล่งต้นตอได้โดยไม่หลง",
    'quiz.q5': 'คุณรู้สึกมั่นใจในการเขียนสรุปเหตุการณ์ทางเทคนิค (Incident Memo) ในระดับใด?',
    'quiz.q5_o1': "ฉันไม่เคยเขียนรายงานเทคนิคตอนเกิดเหตุฉุกเฉินเลย",
    'quiz.q5_o2': "เขียนได้ แต่อาจจะยาวเกินไปหรือไม่ค่อยมีโครงสร้างที่ชัดเจน",
    'quiz.q5_o3': "ฉันสามารถเขียน Technical Memo สรุปปัญหา 1 หน้ากระดาษได้อย่างเฉียบคม",
    'quiz.q6': 'คุณมีความเข้าใจในหลักปฏิบัติของ Responsible AI มากน้อยเพียงใด?',
    'quiz.q6_o1': "ฉันไม่คุ้นเคยกับการออกแบบฟีเจอร์โดยคำนึงถึงความยุติธรรมและอคติ",
    'quiz.q6_o2': "พอรู้ทฤษฎีพื้นฐาน แต่ยังไม่มีประสบการณ์ในการประเมิน AI Bias จริงๆ",
    'quiz.q6_o3': "ฉันเข้าใจวิธีออกแบบและประเมินฟีเจอร์เพื่อหลีกเลี่ยงอคติและรักษาความยุติธรรม"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'en' ? 'th' : 'en'));
  };

  const t = (key) => {
    return dictionary[language]?.[key] || dictionary['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
